request: { socket:
   { _handle:
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _writeRequests: [ [Object] ],
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 2210,
     bytesWritten: 1474,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     remoteAddress: '127.0.0.1',
     remotePort: 63249,
     server:
      { connections: 1,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext:
      { _idleNext: [Circular],
        _idlePrev: [Circular],
        ontimeout: [Function] },
     _idlePrev:
      { _idleNext: [Circular],
        _idlePrev: [Circular],
        ontimeout: [Function] },
     _idleStart: Tue, 20 Sep 2011 13:44:38 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: null },
  connection:
   { _handle:
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _writeRequests: [ [Object] ],
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 2210,
     bytesWritten: 1474,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     remoteAddress: '127.0.0.1',
     remotePort: 63249,
     server:
      { connections: 1,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext:
      { _idleNext: [Circular],
        _idlePrev: [Circular],
        ontimeout: [Function] },
     _idlePrev:
      { _idleNext: [Circular],
        _idlePrev: [Circular],
        ontimeout: [Function] },
     _idleStart: Tue, 20 Sep 2011 13:44:38 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: null },
  httpVersion: '1.1',
  complete: false,
  headers:
   { host: 'localhost',
     connection: 'keep-alive',
     accept: '*/*',
     'user-agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.163 Safari/535.1',
     'accept-encoding': 'gzip,deflate,sdch',
     'accept-language': 'en-US,en;q=0.8',
     'accept-charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3' },
  trailers: {},
  readable: true,
  url: '/favicon.ico',
  method: 'GET',
  statusCode: null,
  client:
   { _handle:
      { writeQueueSize: 0,
        socket: [Circular],
        onread: [Function: onread] },
     _writeRequests: [ [Object] ],
     _flags: 0,
     _connectQueueSize: 0,
     destroyed: false,
     bytesRead: 2210,
     bytesWritten: 1474,
     allowHalfOpen: true,
     writable: true,
     readable: true,
     remoteAddress: '127.0.0.1',
     remotePort: 63249,
     server:
      { connections: 1,
        allowHalfOpen: true,
        _handle: [Object],
        _events: [Object],
        httpAllowHalfOpen: false },
     ondrain: [Function],
     _idleTimeout: 120000,
     _idleNext:
      { _idleNext: [Circular],
        _idlePrev: [Circular],
        ontimeout: [Function] },
     _idlePrev:
      { _idleNext: [Circular],
        _idlePrev: [Circular],
        ontimeout: [Function] },
     _idleStart: Tue, 20 Sep 2011 13:44:38 GMT,
     _events: { timeout: [Function], error: [Function], close: [Function] },
     ondata: [Function],
     onend: [Function],
     _httpMessage: null },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  upgrade: false }